<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!-- DO NOT EDIT: file automatically generated by ucampas from
     /auto/userfiles/ms705/dynamic_html/public_html/survey/index-b.html -->
<html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml"><head><meta content="text/html; charset=UTF-8" http-equiv="Content-Type" /><meta content="text/css" http-equiv="Content-Style-Type" /><title>Computer Laboratory: Personal Storage Survey</title><link href="http://www.cl.cam.ac.uk/style/layout.css" media="all" rel="stylesheet" type="text/css" /><link href="http://www.cl.cam.ac.uk/style/print.css" media="print" rel="stylesheet" type="text/css" /><!--[if IE 6]><link rel="stylesheet" href="http://www.cl.cam.ac.uk/style/ie6.css" type="text/css" media="screen" /><script type="text/javascript" src="http://www.cam.ac.uk/global/js/minmax.js"></script><![endif]--><!--[if IE 7]><link rel="stylesheet" href="http://www.cl.cam.ac.uk/style/ie7.css" type="text/css" media="screen" /><![endif]-->

<link type="text/css" href="css/custom-theme/jquery-ui-1.8.4.custom.css" rel="stylesheet" />	
<link rel="stylesheet" href="css/validationEngine.jquery.css" type="text/css" media="screen" title="no title" charset="utf-8" />
<!--<link rel="stylesheet" href="css/template.css" type="text/css" media="screen" title="no title" charset="utf-8" />-->

<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="jquery-ui.js"></script>
<script src="jquery.validationEngine-en.js" type="text/javascript"></script>
<script src="jquery.validationEngine.js" type="text/javascript"></script>

<style>
.questions {
   border: 1px solid lightgray;
}

.qcatheader, .qcatheader a {
   background-color: lightgray;
   color: black;
}

.qcatbody {
/*   margin-bottom: 10px;*/
}

.qcatbody p {
   margin-left: 5px;
}

.qcatbody table {
   width: 100%;
}

.qcatbody td {
   border-top: 1px solid lightgray;
}

input {
   border: 1px solid black;
}

.qoptional {
   background-color: lightyellow;
}

</style>

</head>


<body class="one-col dept">
<div id="skip"> <a accesskey="2" href="#skip-content">Skip to content</a>&#160;|&#160;<a accesskey="0" href="http://www.cam.ac.uk/site/accesskeys.html">Access key help</a> </div><div id="header">  <div id="branding"><a accesskey="1" href="http://www.cam.ac.uk/"><img alt="University of Cambridge" class="ucam" src="http://www.cl.cam.ac.uk/images/identifier.gif" /></a>
  </div>

    <div id="site-search">
    <form action="http://web-search.cam.ac.uk/query.html" method="get">      <fieldset>      <label for="search-term">Search</label>
      <input accesskey="4" id="search-term" name="qt" type="text" value="" />      <input alt="Search" id="search-button" src="http://www.cl.cam.ac.uk/images/button-search.gif" title="Search" type="image" value="Search" />
      

      </fieldset>
    </form>

  
  </div>
</div>

<div id="dept-title"><h1><a href=".">Computer Laboratory</a></h1>
</div>

<div id="container"> <a id="skip-content" name="skip-content"></a>
<ul id="nav-breadcrumb"><li class="first"><a href="http://www.cl.cam.ac.uk">Computer Laboratory</a></li><li><a href="http://www.cl.cam.ac.uk/~ms705/">Malte Schwarzkopf</a></li><li><a href="http://www.cl.cam.ac.uk/~ms705/research/">Research</a></li><li><a href=".">Personal Storage Study</a></li></ul>

<div id="content">
<div id="content-primary">

<!-- ########################### CONTENT ################################### -->

<h1>Personal Storage Study</h1>

<h3>Thanks for participating!</h3>

<script type="text/javascript">
jQuery(document).ready(function(){

   $("#questionform").validationEngine()

   //$.validationEngine.loadValidation("#date")
   //alert($("#formID").validationEngine({returnIsValid:true}))
   //$.validationEngine.buildPrompt("#date","This is an example","error")	 		 // Exterior prompt build example
   //$.validationEngine.closePrompt(".formError",true) 							// CLOSE ALL OPEN PROMPTS


   function toggleOptional(checkbox, target) {
      if($(checkbox).attr('checked')) {
         $(target).show();
      } else {
         $(target).hide();
      }
   }

	$('.questions .qcatheader').click(function() {
		$(this).next().toggle('slow');
		return false;
	}).next().show();

   // checkboxes toggle number boxes
   $('#chk_desktops').click(function() {
      toggleOptional(this, '#num_desktops');
   });
   $('#chk_laptops').click(function() {
      toggleOptional(this, '#num_laptops');
   });
   $('#chk_smartphone').click(function() {
      toggleOptional(this, '#details_smartphone');
   });
   $('#chk_mp3player').click(function() {
      toggleOptional(this, '#details_mp3player');
   });

   $('#chk_s_fb').click(function() {
      toggleOptional(this, '#s_fb_opt');
   });
   $('#chk_s_google').click(function() {
      toggleOptional(this, '#s_google_opt');
   });
   $('#chk_s_bing').click(function() {
      toggleOptional(this, '#s_bing_opt');
   });
   $('#chk_s_yahoo').click(function() {
      toggleOptional(this, '#s_yahoo_opt');
   });

   // hide them initially
   $('#num_desktops').hide();
   $('#num_laptops').hide();
   $('#details_smartphone').hide();
   $('#details_mp3player').hide();
   // hide optional bits by default
   //$('.qoptional').hide();
   $('#s_fb_opt').hide();
   $('#s_google_opt').hide();
   $('#s_bing_opt').hide();
   $('#s_yahoo_opt').hide();

   // slider setup
	$(function() {
		$(".trustslider").slider({
			value:3,
			min: 0,
			max: 6,
			slide: function(event, ui) {
				tval = parseInt(ui.value);
            switch (tval) {
               case 0:
                  $(this).next().val("None at all");
                  break;
               case 1:
                  $(this).next().val("Very little");
                  break;
               case 2:
                  $(this).next().val("Little");
                  break;
               case 3:
                  $(this).next().val("No indication");
                  break;
               case 4:
                  $(this).next().val("Some");
                  break;
               case 5:
                  $(this).next().val("Reasonably much");
                  break;
               case 6:
                  $(this).next().val("Very much");
                  break;
               default:
                  $(this).next().val("Unknown?! (" + ui.value + ")");
            }
			}
		});
      // slider value init
		$("#s_fb_trustlbl").val("No indication");
		$("#s_google_trustlbl").val("No indication");
		$("#s_bing_trustlbl").val("No indication");
		$("#s_yahoo_trustlbl").val("No indication");
	});

});

// form submission
function submitAndStop() {
   document.questionform.action = 'survey2a.php';
}

function submitAndNext() {
   document.questionform.action = 'survey2b.php';
}

</script>

<form name="questionform" method="POST" action="">
<div class="questions">
    <h3 class="qcatheader"><a href="#">Devices you use</a></h3>
    <div class="qcatbody">
      <p>Please indicate what devices holding and processing personal data you regularly use.</p>
      <table>
         <tr>
            <th>
            </th>
            <th style="width: 50%; background-color: lightyellow; color: orange;">Optional
            </th>
         </tr>
         <tr>
            <td>
               <input type="checkbox" name="chk_desktops" id="chk_desktops" /> Desktop PC(s)
            </td>
            <td class="qoptional">
               <div id="num_desktops">
                  Number: <input type="text" name="txt_numDesktops" class="validate[custom[onlyNumber],length[0,3]] text-input" size="3" id="txt_numDesktops" /><br />
               </div>
            </td>
         </tr>
         <tr>
            <td>
               <input type="checkbox" name="chk_laptops" id="chk_laptops" /> Laptop(s)
            </td>
            <td class="qoptional">
               <div id="num_laptops">
                  Number: <input type="text" name="txt_numLaptops" size="3" /><br />
               </div>
            </td>
         </tr>
         <tr>
            <td>
               <input type="checkbox" name="chk_smartphone" id="chk_smartphone" /> Smartphone (iPhone, Android, Windows Mobile, Nokia, etc.)
            </td>
            <td class="qoptional">
               <div id="details_smartphone">
                  <input type="checkbox" name="chk_sp_iphone" /> iPhone  <br />
                  <input type="checkbox" name="chk_sp_android" /> Android-based phone  <br />
                  <input type="checkbox" name="chk_sp_windows" /> Windows Mobile phone  <br />
                  <input type="checkbox" name="chk_sp_nokia" /> Nokia S60/Symbian/Maemo  <br />
               </div>
            </td>
         </tr>
         <tr>
            <td>
               <input type="checkbox" name="chk_mp3player" id="chk_mp3player" /> Portable music player
            </td>
            <td class="qoptional">
               <div id="details_mp3player">
                  <input type="checkbox" name="chk_mp3_ipod" /> iPod  <br />
                  <input type="checkbox" name="chk_mp3_other" /> Other portable music player  <br />
               </div>
            </td>
         </tr>
         <tr>
            <td>
               <input type="checkbox" name="chk_smartphone" id="chk_smartphone" /> USB memory stick(s)
            </td>
            <td class="qoptional">
            </td>
         </tr>
      </table>
    </div>
    <h3 class="qcatheader"><a href="#">Services you use</a></h3>
    <div class="qcatbody">
      <p>Please indicate which of the following online services you regularly use. You can specify further details (e.g. what particular services you are using) once you tick them.</p>
      <table>
         <tr>
            <th>
            </th>
            <th style="width: 50%; background-color: lightyellow; color: orange;">Optional
            </th>
         </tr>
         <tr>
            <td>
               <input type="checkbox" id="chk_s_fb" /> Facebook
            </td>
            <td class="qoptional">
               <div id="s_fb_opt">
                  Number of pictures/videos: 
                     <select>
                        <option>0 (None)</option>
                        <option>0-10</option>
                        <option>10-100</option>
                        <option>100-500</option>
                        <option>More than 500</option>
                     </select>
                  <div style="margin-top: 5px;">
                     <label for="s_fb_trustsl" style="float: left; margin-right: 20px;">Trust:</label>
                     <div style="width: 200px; float: left;  margin-right: 20px; top: 3px;" class="trustslider" id="s_fb_trustsl"></div>
                     <input type="text" id="s_fb_trustlbl" style="border:0; color:#f6931f; font-weight:bold; width:120px; float: left;" />
                  </div>
               </div>
            </td>
         </tr>
         <tr>
            <td>
               <input type="checkbox" id="chk_s_google" /> Google
            </td>
            <td class="qoptional">
               <div id="s_google_opt">
                  Services you use: <br />
                  <input type="checkbox" id="chk_s_google_search" /> Search
                  <input type="checkbox" id="chk_s_google_gmail" /> Gmail
                  <input type="checkbox" id="chk_s_google_maps" /> Google Maps <br />
                  <input type="checkbox" id="chk_s_google_docs" /> Google Docs
                  <input type="checkbox" id="chk_s_google_latitude" /> Google Latitude
                  <input type="checkbox" id="chk_s_google_latitude" /> YouTube (upload)
                  <hr />
                  <div style="margin-top: 5px;">
                     <label for="s_google_trustsl" style="float: left; margin-right: 20px;">Trust:</label>
                     <div style="width: 200px; float: left;  margin-right: 20px; top: 3px;" class="trustslider" id="s_google_trustsl"></div>
                     <input type="text" id="s_google_trustlbl" style="border:0; color:#f6931f; font-weight:bold; width:120px; float: left;" />
                  </div>
               </div>
            </td>
         </tr>
         <tr>
            <td>
               <input type="checkbox" id="chk_s_bing" /> Bing/Microsoft
            </td>
            <td class="qoptional">
               <div id="s_bing_opt">
                  Services you use: <br />
                  <input type="checkbox" id="chk_s_bing_search" /> Bing Search
                  <input type="checkbox" id="chk_s_bing_hotmail" /> Hotmail
                  <input type="checkbox" id="chk_s_bing_maps" /> Bing Maps <br />
                  <input type="checkbox" id="chk_s_bing_docs" /> Docs.com
                  <input type="checkbox" id="chk_s_bing_livemesh" /> Live Mesh
                  <input type="checkbox" id="chk_s_bing_skydrive" /> SkyDrive
                  <hr />
                  <div style="margin-top: 5px;">
                     <label for="s_bing_trustsl" style="float: left; margin-right: 20px;">Trust:</label>
                     <div style="width: 200px; float: left;  margin-right: 20px; top: 3px;" class="trustslider" id="s_bing_trustsl"></div>
                     <input type="text" id="s_bing_trustlbl" style="border:0; color:#f6931f; font-weight:bold; width:120px; float: left;" />
                  </div>
               </div>
            </td>
         </tr>
         <tr>
            <td>
               <input type="checkbox" id="chk_s_yahoo" /> Yahoo!
            </td>
            <td class="qoptional">
               <div id="s_yahoo_opt">
                  Services you use: <br />
                  <input type="checkbox" id="chk_s_yahoo_search" /> Yahoo! Mail
                  <input type="checkbox" id="chk_s_yahoo_hotmail" /> Yahoo! Video (upload)
                  <hr />
                  <div style="margin-top: 5px;">
                     <label for="s_yahoo_trustsl" style="float: left; margin-right: 20px;">Trust:</label>
                     <div style="width: 200px; float: left;  margin-right: 20px; top: 3px;" class="trustslider" id="s_yahoo_trustsl"></div>
                     <input type="text" id="s_yahoo_trustlbl" style="border:0; color:#f6931f; font-weight:bold; width:120px; float: left;" />
                  </div>
               </div>
            </td>
         </tr>
         <tr>
            <td>
               <input type="checkbox" /> Twitter
            </td>
            <td class="qoptional">
            </td>
         </tr>
         <tr>
            <td>
               <input type="checkbox" /> Others
            </td>
            <td class="qoptional">
            </td>
         </tr>
      </table>
    </div>
</div>

<br />

<p>Thank you very much for completing the survey. In the second part of our study, we ask you to run a small tool that will gather some information on your computers. The tool will not access or transmit any personal information, and you can ask it to only submit aggregate information. However, we are aware that you might not be happy to do this, so you can skip the second stage and still contribute.</p>

<div style="text-align: right;">
<input type="submit" value="No, I'd rather stop here" style="background-color: darkred; color: white; font-size: 12pt;" onClick="return submitAndStop();" />
   
<input type="submit" value="Yes, proceed to second stage" style="background-color: darkgreen; color: white; font-size: 12pt;" onClick="return submitAndNext();" />
</div>

</form>

<br />

<!-- ########################### /CONTENT ################################## -->


<hr />
<div style="font-size: 80%; color: gray;"><p>This research is done by <strong>Malte Schwarzkopf</strong> and <strong>Dr Steven Hand</strong> at the University of Cambridge Computer Laboratory. If you have any questions or would like to learn more, please contact Malte directly:</p>

<p><strong>Email:</strong><br /><img class="aleft" src="cl-email-grey.png" style="border: none; float: none;" /></p>

<p><strong>Postal address:</strong><br />Malte Schwarzkopf<br />University of Cambridge Computer Laboratory<br />Willam Gates Building<br />15 JJ Thomson Avenue<br />Cambridge CB3 0FD, UK<br />Tel.: +44 1223 763683
</p>
</div>

</div></div>

<ul id="site-info"><li class="copy">&#169; 2010 Computer Laboratory, University of Cambridge<br />Information provided by <a href="http://www.cl.cam.ac.uk/~ms705/">Malte Schwarzkopf</a></li></ul>
</div>
</body></html>
