<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!-- DO NOT EDIT: file automatically generated by ucampas from
     /auto/userfiles/ms705/dynamic_html/public_html/survey/index-b.html -->
<html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml"><head><meta content="text/html; charset=UTF-8" http-equiv="Content-Type" /><meta content="text/css" http-equiv="Content-Style-Type" /><title>Computer Laboratory: Personal Storage Survey</title><link href="http://www.cl.cam.ac.uk/style/layout.css" media="all" rel="stylesheet" type="text/css" /><link href="http://www.cl.cam.ac.uk/style/print.css" media="print" rel="stylesheet" type="text/css" /><!--[if IE 6]><link rel="stylesheet" href="http://www.cl.cam.ac.uk/style/ie6.css" type="text/css" media="screen" /><script type="text/javascript" src="http://www.cam.ac.uk/global/js/minmax.js"></script><![endif]--><!--[if IE 7]><link rel="stylesheet" href="http://www.cl.cam.ac.uk/style/ie7.css" type="text/css" media="screen" /><![endif]-->

<link type="text/css" href="css/custom-theme/jquery-ui-1.8.4.custom.css" rel="stylesheet" />	
<link rel="stylesheet" href="css/validationEngine.jquery.css" type="text/css" media="screen" title="no title" charset="utf-8" />
<!--<link rel="stylesheet" href="css/template.css" type="text/css" media="screen" title="no title" charset="utf-8" />-->

<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="jquery-ui.js"></script>
<script src="jquery.validationEngine-en.js" type="text/javascript"></script>
<script src="jquery.validationEngine.js" type="text/javascript"></script>

<style>
.questions {
   border: 1px solid lightgray;
}

.qcatheader, .qcatheader a {
   background-color: lightgray;
   color: black;
}

.qcatbody {
/*   margin-bottom: 10px;*/
}

.qcatbody p {
   margin-left: 5px;
}

.qcatbody table {
   width: 100%;
}

.qcatbody td {
   border-top: 1px solid lightgray;
}

.qoptional {
   background-color: lightyellow;
}

.machinetable {
   border-collapse: collapse;
   position: relative;
   margin: auto;
}

.machinetable th {
   border: 1px solid gray;
   background-color: lightgray;
}

.machinetable td {
   border: 1px solid gray;
   vertical-align: middle;
}

#download-button {
   width: 300px;
   height: 50px;
   font-weight: bold;
   font-size: 16pt;
   margin: auto;
   position: relative;
}

#download-table {
   border-collapse: collapse;
}
#download-table td, #download-table th {
   border: 1px dotted black;
}

</style>

</head>


<body class="one-col dept">
<div id="skip"> <a accesskey="2" href="#skip-content">Skip to content</a>&#160;|&#160;<a accesskey="0" href="http://www.cam.ac.uk/site/accesskeys.html">Access key help</a> </div><div id="header">  <div id="branding"><a accesskey="1" href="http://www.cam.ac.uk/"><img alt="University of Cambridge" class="ucam" src="http://www.cl.cam.ac.uk/images/identifier.gif" /></a>
  </div>

    <div id="site-search">
    <form action="http://web-search.cam.ac.uk/query.html" method="get">      <fieldset>      <label for="search-term">Search</label>
      <input accesskey="4" id="search-term" name="qt" type="text" value="" />      <input alt="Search" id="search-button" src="http://www.cl.cam.ac.uk/images/button-search.gif" title="Search" type="image" value="Search" />
      

      </fieldset>
    </form>

  
  </div>
</div>

<div id="dept-title"><h1><a href=".">Computer Laboratory</a></h1>
</div>

<div id="container"> <a id="skip-content" name="skip-content"></a>
<ul id="nav-breadcrumb"><li class="first"><a href="http://www.cl.cam.ac.uk">Computer Laboratory</a></li><li><a href="http://www.cl.cam.ac.uk/~ms705/">Malte Schwarzkopf</a></li><li><a href="http://www.cl.cam.ac.uk/~ms705/research/">Research</a></li><li><a href=".">Personal Storage Study</a></li></ul>

<div id="content">
<div id="content-primary">

<!-- ########################### CONTENT ################################### -->

<?php

require("savedata.inc.php");

if (!isset($_GET['token'])) {
   $ds = new DataSubmitter();
   $ds->submit($_POST);
} else {
   $ds = new DataSubmitter($_GET['token']);
   if ($_GET['a'] == 'update') {
      $ds->submitDevices($_POST);
   }
}

?>

<script type="text/javascript">
jQuery(document).ready(function(){
	$('.qcatheader').click(function() {
		$(this).next().toggle('fast');
		return false;
	}).next().hide();

	$('.os_win').click(function() {
      setDisplayOS($(this).attr('num'), 0);
		return false;
	});
	$('.os_mac').click(function() {
      setDisplayOS($(this).attr('num'), 1);
		return false;
	});
	$('.os_lin').click(function() {
      setDisplayOS($(this).attr('num'), 2);
		return false;
	});
	$('.os_other').click(function() {
      setDisplayOS($(this).attr('num'), 3);
		return false;
	});

	$('#emaillink').click(function() {
		$(this).next().toggle('fast');
		return false;
	}).next().hide();

   $("#downloadDialog").dialog({
      autoOpen: false,
	   height: 340,
      width: 450,
	   modal: true,
      show: "fold",
      hide: "explode"
   });

<?php
   $machines = $ds->getMachineDescriptors();
   $i = 1;
   foreach ($machines as $m) {
?>
   setDisplayOS(<?php echo $i; ?>, <?php echo $m['os']; ?>);
<?php
      $i++;
   }
?>

});

var check;
function checkDataUploaded(token, handler, handlerUsesTokens) {

   function test(data) {
      check = parseInt(data);
      if (handlerUsesTokens) {
         handler(token, (check > 0));
      } else {
         handler(tokenToDevID(token), (check > 0));
      }
   }

   $.get('util.php?a=check&token=' + token, test);

}

function setUploadStatus(devid, uploaded) {
   if (uploaded) {
      $('#status' +  devid).css("background-color", "lightgreen").text("Data uploaded!");
   } else {
      $('#status' +  devid).css("background-color", "white").text("");
   }
}

function setDisplayOS(devid, osid) {
   $("#osselect" + devid).val(osid);
   
   switch (osid) {
      case 0:  // Windows
		   $('.osicon' + devid).attr('src', 'images/icon_windows.gif');
		   $('#dl-' +  devid).show().css("background-color", "white");
		   $('#status' +  devid).css("background-color", "white");
         checkDataUploaded(devIDToToken(devid), setUploadStatus, false);
      break;

      case 1:  // Mac OS
		   $('.osicon' + devid).attr('src', 'images/icon_macos.gif');
		   $('#dl-' +  devid).show().css("background-color", "white");
		   $('#status' +  devid).css("background-color", "white");
         checkDataUploaded(devIDToToken(devid), setUploadStatus, false);
      break;

      case 2:  // Linux
		   $('.osicon' + devid).attr('src', 'images/icon_linux.gif');
		   $('#dl-' +  devid).show().css("background-color", "white");
		   $('#status' +  devid).css("background-color", "white");
         checkDataUploaded(devIDToToken(devid), setUploadStatus, false);
      break;

      case 3:  // Other
	      $('.osicon' + devid).attr('src', 'images/icon_other.gif');
	      $('#dl-' +  devid).hide().css("background-color", "gray");
	      $('#status' +  devid).text("Not supported!").css("background-color", "gray");
      break;

      default:
         checkDataUploaded('<?php echo strtoupper($m['token']); ?>', setUploadStatus, false);

   }
}

function openDLDialog(id, token) {
   $.get('download.php?token=' + token + '&id=' + id, function(data) {
      $("#dl-contents").html(data);
   });   
	$("#downloadDialog").dialog("open");
	return false;
}

function downloadSelectionOptions(id, token) {
   $.get('download.php?token=' + token + '&id=' + id + '&sel=1', function(data) {
      $("#dl-contents").html(data);
   });   
	//$("#downloadDialog").dialog("open");
	return false;
}

function initiateDownload(osid, bits, token) {
   $("#download-button").attr('disabled', 'disabled');
   var clientfile="";
   switch (osid) {
      case 0:  // Windows
         clientfile = "scanclient-win" + bits + ".exe";
      break;

      case 1:  // Mac OS
         clientfile = "scanclient-mac32.dmg";
      break;

      case 2:  // Linux
         clientfile = "scanclient-lin" + bits + ".tar.gz";
      break;

      case 3:  // Other
         alert("Unrecognised operating system. Please use the manual download facility, or email malte.schwarzkopf@cl.cam.ac.uk to receive help.");
         downloadSelectionOptions(osid, '');
      break;

      default:
   }

   window.location.href = 'clients/' + clientfile;
   waitForResults(token);

	return false;
}

function waitForResults(token) {

   // timer
   var intID = setInterval(checkForResult, 5000);

   function checkForResult() {

      checkDataUploaded(token, function(token, status) {
         if (status) {
            // show completion message in dialog
            $.get('util.php?a=waitdone&token=' + token, function(data) {
                  $("#dl-contents").html(data);
               });
            clearInterval(intID);
         } else {
            $.get('util.php?a=wait&token=' + token, function(data) {
                  $("#dl-contents").html(data);
               });
         }
      }, true);

   }

}

function closeDLDialog(token) {
   // close the dialog
   $("#downloadDialog").dialog("close");

   // update the row in the main page table
   $('#status' +  tokenToDevID(token)).text("Data uploaded").css("background-color", "lightgreen");
}


function sendTokenEmail() {
   var address = $('input[name="useremail"]').attr("value");
   var usertoken = $('#usertoken').text();

   if (address == "") {
      alert('No email address entered!');
      return;
   }

   //alert("ad: " + address + ", token: " + usertoken);
   $.get('util.php?a=sendmail&token=' + usertoken + '&email=' + address, function(data) {
      alert('Sent an email to ' + address + '.');
   });   
}

function saveMachineLabel(token, label) {
   //alert('util.php?token=' + token + '&label=' + label);
   $.get('util.php?a=savelabel&token=' + token + '&label=' + label, function(data){
      //alert("Data Loaded: " + data);
   });
}

function saveMachineOS(token, osid) {
   //alert('util.php?token=' + token + '&os=' + osid);
   $.get('util.php?a=saveos&token=' + token + '&os=' + osid, function(data){
      //alert("Data Loaded: " + data);
   });
}

function tokenToDevID(token) {
<?php
   $i = 1;
   foreach ($machines as $m) {
?>
   if (token == '<?php echo strtoupper($m['token']); ?>') {
      return <?php echo $i; ?>;
   }
<?php
   $i++;
   }
?>
}

function devIDToToken(devid) {
<?php
   $i = 1;
   foreach ($machines as $m) {
?>
   if (devid == <?php echo $i; ?>) {
      return '<?php echo strtoupper($m['token']); ?>';
   }
<?php
   $i++;
   }
?>
}

</script>

<div style="float: right; font-size: 22pt;">
<span style="color: lightgray; font-size: 18pt;">Page</span> <span style="color: lightgray;">2</span><span style="color: lightgray;">/3</span>
</div>

<h1>Personal Storage Study</h1>

<h3>Thanks for agreeing to continue!</h3>

<?php 
if (!isset($_GET['token'])) {
?>
<p>Thank you very much for completing the survey. Your data has been submitted to the researchers. If you would like to review the exact data submitted, you can do so below.</p>

<h3 class="qcatheader" style="font-size: 10pt;"><a href="#">Click here to review the exact data submitted from the first stage</a></h3>
<div class="qcatbody questions">
   <pre>
<?php

var_dump($_POST);

?>
   </pre>
</div>
<?php
} else {
?>

<p>Thank you very much for completing the survey. The first part of your data has been submitted to the researchers.</p>

<?php
}
?>

<br />

<h3>Stage 2 &ndash; Running the Analysis Tool</h3>

<?php

$num_desktops = ($_POST['txt_numDesktops'] != '') ? $_POST['txt_numDesktops'] : 0;
$num_laptops = ($_POST['txt_numLaptops'] != '') ? $_POST['txt_numLaptops'] : 0;
$num_computers = $num_desktops + $num_laptops;

$usertoken = $ds->get_user_token();

if ($num_computers == 0 && !isset($_GET["token"])) {
?>
<div class="warning">
   <div class="alert">
      You did not specify the number of desktop and laptop computers you use on the previous page. 
      However, to continue, we need an indication about how many computers you are going to run the
      analysis tool on. Please supply this information below.
   </div>
   <form method="POST" action="survey2b.php?token=<?php echo $usertoken; ?>&a=update">
      <div style="text-align: center;">
         Desktops: <input type="text" name="txt_numDesktops" size="2" /> 
         Laptops: <input type="text" name="txt_numLaptops" size="2" />
         <input type="submit" value="Update" />
      </div>
      <br />
   </form>
</div>


<?php
} else {

   $machines = $ds->getMachineDescriptors();

?>

<p>
<div style="text-align: center; border: 2px solid orange; background-color: lightyellow; padding: 3px;">
   <div style="font-size: 16pt; margin-top: 8px;">Your <em>user token</em> is: <b><span id="usertoken"><?php echo strtoupper($usertoken); ?></span></b></div>
   <p>You will need this token to get back to this page in order to download the analysis tool again (for running
      it on another machine, or to run it again later).
   </p>
   <p id="emaillink"><a href="">Click here if you would like a link to this page to be emailed to you</a>. [N.B.: We will not store your email address]</p>
   <p>Your email address: <input type="text" name="useremail" /> <input type="submit" value="Send" onClick="sendTokenEmail();" /></p>
</div>
</p>

<br />

<p>Please download the survey tool on each of your machines and run it, entering
the machine token. This will scan your machine and provide us with some 
anonymised data about how you utilise personal storage (click <b>&raquo;</b> <a href="">here</a> to see 
exactly what data is going to be gathered).</p>

<div style="text-align: center;">
<table class="machinetable">
   <tr>
      <th>Machine ID</th>
      <th style="width: 70px;">Type</th>
      <th>Operating System</th>
      <th>Machine Token</th>
      <th></th>
      <th style="width: 100px;">Status</th>
   </tr>
<?php
   $i = 1;
   foreach ($machines as $m) {
?>
   <tr>
      <td><?php echo $i; ?>: <input type="text" name="m<?php echo $i; ?>name" size="8" onBlur="saveMachineLabel('<?php echo $m['token']; ?>', this.value);" value="<?php echo $m['label']; ?>" /></td>
      <td><img src="images/<?php echo ($m['type'] == 0) ? 'desktop' : 'laptop'; ?>.png" align="middle" style="float: left;" /> <?php echo ($m['type'] == 0) ? 'Desktop' : 'Laptop'; ?></td>
      <td>
         <img src="images/icon_windows.gif" class="osicon<?php echo $i;?>" style="float: left;" /> &nbsp;
         <select id="osselect<?php echo $i;?>" onBlur="saveMachineOS('<?php echo $m['token']; ?>', this.selectedIndex);" style="float: left;">
            <option class="os_win" value="0" num="<?php echo $i;?>">Windows</option>
            <option class="os_mac" value="1" num="<?php echo $i;?>">Mac OS X</option>
            <option class="os_lin" value="2" num="<?php echo $i;?>">Linux</option>
            <option class="os_other" value="3" num="<?php echo $i;?>">Other</option>
         </select>
      </td>
      <td><strong><?php echo strtoupper($m['token']); ?></strong></td>
      <td><a href="" onClick="openDLDialog(<?php echo $i.',\''.$m['token'].'\''; ?>); return false;" id="dl-<?php echo $i;?>">Download...</a></td>
      <td id="status<?php echo $i;?>"></td>
   </tr>
<?php      
      $i++;
   }
?>
</table>
</div>

<div id="downloadDialog" title="Download scanning client">
   <div id="dl-contents">Loading...</div>
</div>

<br />

<p>Thank you very much for completing the second stage. Once you have uploaded the data for your machines above, you can finalize your participation in the study. On the next page, we will ask for any final comments and give you an opportunity to voluntarily provide us with contact details for a second run in the future.</p>

<form method="POST" action="survey3.php">
<div style="text-align: right;">
<input type="hidden" name="usertoken" value="<?php echo $usertoken; ?>" />
<input type="submit" value="Proceed to final stage" style="background-color: darkgreen; color: white; font-size: 12pt;" />
</div>
</form>

<?php
}
?>


<!-- ########################### /CONTENT ################################## -->


<hr />
<div style="font-size: 80%; color: gray;"><p>This research is done by <strong>Malte Schwarzkopf</strong> and <strong>Dr Steven Hand</strong> at the University of Cambridge Computer Laboratory. If you have any questions or would like to learn more, please contact Malte directly:</p>

<p><strong>Email:</strong><br /><img class="aleft" src="cl-email-grey.png" style="border: none; float: none;" /></p>

<p><strong>Postal address:</strong><br />Malte Schwarzkopf<br />University of Cambridge Computer Laboratory<br />Willam Gates Building<br />15 JJ Thomson Avenue<br />Cambridge CB3 0FD, UK<br />Tel.: +44 1223 763683
</p>
</div>

</div></div>

<ul id="site-info"><li class="copy">&#169; 2010 Computer Laboratory, University of Cambridge<br />Information provided by <a href="http://www.cl.cam.ac.uk/~ms705/">Malte Schwarzkopf</a></li></ul>
</div>
</body></html>
