<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!-- DO NOT EDIT: file automatically generated by ucampas from
     /auto/userfiles/ms705/dynamic_html/public_html/survey/index-b.html -->
<html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml"><head><meta content="text/html; charset=UTF-8" http-equiv="Content-Type" /><meta content="text/css" http-equiv="Content-Style-Type" /><title>Computer Laboratory: Personal Storage Survey</title><link href="http://www.cl.cam.ac.uk/style/layout.css" media="all" rel="stylesheet" type="text/css" /><link href="http://www.cl.cam.ac.uk/style/print.css" media="print" rel="stylesheet" type="text/css" /><!--[if IE 6]><link rel="stylesheet" href="http://www.cl.cam.ac.uk/style/ie6.css" type="text/css" media="screen" /><script type="text/javascript" src="http://www.cam.ac.uk/global/js/minmax.js"></script><![endif]--><!--[if IE 7]><link rel="stylesheet" href="http://www.cl.cam.ac.uk/style/ie7.css" type="text/css" media="screen" /><![endif]-->

<link type="text/css" href="css/custom-theme/jquery-ui-1.8.4.custom.css" rel="stylesheet" />	
<link rel="stylesheet" href="css/validationEngine.jquery.css" type="text/css" media="screen" title="no title" charset="utf-8" />
<!--<link rel="stylesheet" href="css/template.css" type="text/css" media="screen" title="no title" charset="utf-8" />-->

<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="jquery-ui.js"></script>
<script src="jquery.validationEngine-en.js" type="text/javascript"></script>
<script src="jquery.validationEngine.js" type="text/javascript"></script>

<style>
.questions {
   border: 1px solid lightgray;
}

.qcatheader, .qcatheader a {
   background-color: lightgray;
   color: black;
}

.qcatbody {
/*   margin-bottom: 10px;*/
}

.qcatbody p {
   margin-left: 5px;
}

.qcatbody table {
   width: 100%;
}

.qcatbody td {
   border-top: 1px solid lightgray;
}

input {
   border: 1px solid black;
}

.qoptional {
   background-color: lightyellow;
}

</style>

</head>


<body class="one-col dept">
<div id="skip"> <a accesskey="2" href="#skip-content">Skip to content</a>&#160;|&#160;<a accesskey="0" href="http://www.cam.ac.uk/site/accesskeys.html">Access key help</a> </div><div id="header">  <div id="branding"><a accesskey="1" href="http://www.cam.ac.uk/"><img alt="University of Cambridge" class="ucam" src="http://www.cl.cam.ac.uk/images/identifier.gif" /></a>
  </div>

    <div id="site-search">
    <form action="http://web-search.cam.ac.uk/query.html" method="get">      <fieldset>      <label for="search-term">Search</label>
      <input accesskey="4" id="search-term" name="qt" type="text" value="" />      <input alt="Search" id="search-button" src="http://www.cl.cam.ac.uk/images/button-search.gif" title="Search" type="image" value="Search" />
      

      </fieldset>
    </form>

  
  </div>
</div>

<div id="dept-title"><h1><a href=".">Computer Laboratory</a></h1>
</div>

<div id="container"> <a id="skip-content" name="skip-content"></a>
<ul id="nav-breadcrumb"><li class="first"><a href="http://www.cl.cam.ac.uk">Computer Laboratory</a></li><li><a href="http://www.cl.cam.ac.uk/~ms705/">Malte Schwarzkopf</a></li><li><a href="http://www.cl.cam.ac.uk/~ms705/research/">Research</a></li><li><a href=".">Personal Storage Study</a></li></ul>

<div id="content">
<div id="content-primary">

<!-- ########################### CONTENT ################################### -->

<?php

require("savedata.inc.php");

$ds = new DataSubmitter();

?>

<script type="text/javascript">
jQuery(document).ready(function(){
	$('.qcatheader').click(function() {
		$(this).next().toggle('fast');
		return false;
	}).next().hide();
});
</script>

<h1>Personal Storage Study</h1>

<h3>Thanks for agreeing to continue!</h3>

<p>Thank you very much for completing the survey. Your data has been submitted to the researchers. If you would like to review the exact data submitted, you can do so below.</p>

<h3 class="qcatheader" style="font-size: 10pt;"><a href="#">Click here to review the exact data submitted from the first stage</a></h3>
<div class="qcatbody questions">
   <pre>
<?php

var_dump($_POST);

?>
   </pre>
</div>

<br />

<h3>Stage 2 &ndash; Running the Analysis Tool</h3>

<?php

$num_desktops = ($_POST['txt_numDesktops'] != '') ? $_POST['txt_numDesktops'] : 0;
$num_laptops = ($_POST['txt_numLaptops'] != '') ? $_POST['txt_numLaptops'] : 0;
$num_computers = $num_desktops + $num_laptops;

if ($num_computers == 0) {
?>
<div class="warning">
   <div class="alert">
      You did not specify the number of desktop and laptop computers you use on the previous page. 
      Please add your devices manually in the table below.
   </div>
</div>
<?php
} else {

}
?>

<br />

<!-- ########################### /CONTENT ################################## -->


<hr />
<div style="font-size: 80%; color: gray;"><p>This research is done by <strong>Malte Schwarzkopf</strong> and <strong>Dr Steven Hand</strong> at the University of Cambridge Computer Laboratory. If you have any questions or would like to learn more, please contact Malte directly:</p>

<p><strong>Email:</strong><br /><img class="aleft" src="cl-email-grey.png" style="border: none; float: none;" /></p>

<p><strong>Postal address:</strong><br />Malte Schwarzkopf<br />University of Cambridge Computer Laboratory<br />Willam Gates Building<br />15 JJ Thomson Avenue<br />Cambridge CB3 0FD, UK<br />Tel.: +44 1223 763683
</p>
</div>

</div></div>

<ul id="site-info"><li class="copy">&#169; 2010 Computer Laboratory, University of Cambridge<br />Information provided by <a href="http://www.cl.cam.ac.uk/~ms705/">Malte Schwarzkopf</a></li></ul>
</div>
</body></html>
