<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!-- DO NOT EDIT: file automatically generated by ucampas from
     /auto/userfiles/ms705/dynamic_html/public_html/survey/index-b.html -->
<html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml"><head><meta content="text/html; charset=UTF-8" http-equiv="Content-Type" /><meta content="text/css" http-equiv="Content-Style-Type" /><title>Computer Laboratory: Personal Storage Survey</title><link href="http://www.cl.cam.ac.uk/style/layout.css" media="all" rel="stylesheet" type="text/css" /><link href="http://www.cl.cam.ac.uk/style/print.css" media="print" rel="stylesheet" type="text/css" /><!--[if IE 6]><link rel="stylesheet" href="http://www.cl.cam.ac.uk/style/ie6.css" type="text/css" media="screen" /><script type="text/javascript" src="http://www.cam.ac.uk/global/js/minmax.js"></script><![endif]--><!--[if IE 7]><link rel="stylesheet" href="http://www.cl.cam.ac.uk/style/ie7.css" type="text/css" media="screen" /><![endif]-->

<link type="text/css" href="css/custom-theme/jquery-ui-1.8.4.custom.css" rel="stylesheet" />	
<link rel="stylesheet" href="css/validationEngine.jquery.css" type="text/css" media="screen" title="no title" charset="utf-8" />
<!--<link rel="stylesheet" href="css/template.css" type="text/css" media="screen" title="no title" charset="utf-8" />-->

<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="jquery-ui.js"></script>
<script src="jquery.validationEngine-en.js" type="text/javascript"></script>
<script src="jquery.validationEngine.js" type="text/javascript"></script>

<style>
.questions {
   border: 1px solid lightgray;
}

.qcatheader, .qcatheader a {
   background-color: lightgray;
   color: black;
}

.qcatbody {
/*   margin-bottom: 10px;*/
}

.qcatbody p {
   margin-left: 5px;
}

.qcatbody table {
   width: 100%;
}

.qcatbody td {
   border-top: 1px solid lightgray;
}

.qoptional {
   background-color: lightyellow;
}

.machinetable {
   border-collapse: collapse;
   position: relative;
   margin: auto;
}

.machinetable th {
   border: 1px solid gray;
   background-color: lightgray;
}

.machinetable td {
   border: 1px solid gray;
   vertical-align: middle;
}

#download-button {
   width: 300px;
   height: 50px;
   font-weight: bold;
   font-size: 16pt;
   margin: auto;
   position: relative;
}

#download-table {
   border-collapse: collapse;
}
#download-table td, #download-table th {
   border: 1px dotted black;
}

</style>

</head>


<body class="one-col dept">
<div id="skip"> <a accesskey="2" href="#skip-content">Skip to content</a>&#160;|&#160;<a accesskey="0" href="http://www.cam.ac.uk/site/accesskeys.html">Access key help</a> </div><div id="header">  <div id="branding"><a accesskey="1" href="http://www.cam.ac.uk/"><img alt="University of Cambridge" class="ucam" src="http://www.cl.cam.ac.uk/images/identifier.gif" /></a>
  </div>

    <div id="site-search">
    <form action="http://web-search.cam.ac.uk/query.html" method="get">      <fieldset>      <label for="search-term">Search</label>
      <input accesskey="4" id="search-term" name="qt" type="text" value="" />      <input alt="Search" id="search-button" src="http://www.cl.cam.ac.uk/images/button-search.gif" title="Search" type="image" value="Search" />
      

      </fieldset>
    </form>

  
  </div>
</div>

<div id="dept-title"><h1><a href=".">Computer Laboratory</a></h1>
</div>

<div id="container"> <a id="skip-content" name="skip-content"></a>
<ul id="nav-breadcrumb"><li class="first"><a href="http://www.cl.cam.ac.uk">Computer Laboratory</a></li><li><a href="http://www.cl.cam.ac.uk/~ms705/">Malte Schwarzkopf</a></li><li><a href="http://www.cl.cam.ac.uk/~ms705/research/">Research</a></li><li><a href=".">Personal Storage Study</a></li></ul>

<div id="content">
<div id="content-primary">

<!-- ########################### CONTENT ################################### -->

<?php

?>

<div style="float: right; font-size: 22pt;">
<span style="color: lightgray; font-size: 18pt;">Page</span> <span style="color: lightgray;">3</span><span style="color: lightgray;">/3</span>
</div>

<h1>Personal Storage Study</h1>

<h3>Thanks for staying with us so far!</h3>

<p>Thank you very much for completing the survey and submitting data from your machines. This is the final stage &ndash; we will ask you for any other comments and give you an opportunity to give us a way of contacting you if we either conduct a follow-up study or publish results based on the data you provided.</p>

<br />

<h3>Stage 3 &ndash; Final questions</h3>

<form method="POST" action="surveyend.php">
<p>
<div style="border: 2px solid orange; background-color: lightyellow; padding: 3px;">
   <p style="width: 50%; background-color: lightyellow; color: orange; font-weight: bold;">Optional:</p>
   <p>Please provide any final comments that you feel have not been covered by the study until now. This can include anything about your personal storage habits that you deem relevant for research on this topic.</p>
   <textarea name="comments" style="width: 90%; height: 100px;" onClick="if (this.value == 'Your comments here...') { this.value = ''; }">Your comments here...</textarea>
</div>
</p>

<br />

<p>Finally, we are asking you to provide us with an email address. <strong>This will not be associated with the data set created by your participation in the study.</strong> We are asking for it because we may at a later point ask you to participate in a follow-up study that looks at how your personal storage has evolved over time. Of course, participation will be voluntary, and we will not use your email address for any other purposes. It will be stored seperately from the data sets and only used in isolation.</p>

<p>
<div style="border: 2px solid orange; background-color: lightyellow; padding: 3px;">
   <p style="width: 50%; background-color: lightyellow; color: orange; font-weight: bold;">Optional:</p>
   <p>If you consent, please enter your email address here: 
   <input type="text" name="email" style="width: 200px;" /></p>
   <p>Tick this box if you would like to hear about scientific results based on the data you provided being published: <input type="checkbox" name="notify_about_papers" />
</div>
</p>

<br />

<p>Thank you again for supporting our research by providing your data! We appreciate the time and effort you have committed to this.</p>

<div style="text-align: right;">
<input type="hidden" name="usertoken" value="<?php echo $_POST['usertoken']; ?>" />
<input type="submit" value="Finish!" style="background-color: darkgreen; color: white; font-size: 12pt;" />
</div>
</form>


<br />


<!-- ########################### /CONTENT ################################## -->


<hr />
<div style="font-size: 80%; color: gray;"><p>This research is done by <strong>Malte Schwarzkopf</strong> and <strong>Dr Steven Hand</strong> at the University of Cambridge Computer Laboratory. If you have any questions or would like to learn more, please contact Malte directly:</p>

<p><strong>Email:</strong><br /><img class="aleft" src="cl-email-grey.png" style="border: none; float: none;" /></p>

<p><strong>Postal address:</strong><br />Malte Schwarzkopf<br />University of Cambridge Computer Laboratory<br />Willam Gates Building<br />15 JJ Thomson Avenue<br />Cambridge CB3 0FD, UK<br />Tel.: +44 1223 763683
</p>
</div>

</div></div>

<ul id="site-info"><li class="copy">&#169; 2010 Computer Laboratory, University of Cambridge<br />Information provided by <a href="http://www.cl.cam.ac.uk/~ms705/">Malte Schwarzkopf</a></li></ul>
</div>
</body></html>
